### ISSUE TITLE
Daylight savings time issue

### ISSUE THREAD

**Issue by Rulox** [davaxi/VCalendar#2]
Hi,

I've set the timezone to 'America/Los_Angeles' but it's returning me the wrong hour (1 ahead) because right now, in summer, the time is different. Is that a problem of the library or just a php thing? 

Thanks, nice code btw!

**Comment by davaxi** [comment]
Hi,
Good question... Can you send your file ?

**Comment by Rulox** [comment]
I fixed it adding manually to the output the Offset for the timezone, so I'm not using this library anymore. Maybe this will help you if you want to fix it for the lib.

More info -> http://erics-notes.blogspot.com.es/2013/05/fixing-ics-time-zone.html

I had to add when the offset is +1 and when is +0 (for example, second Sunday in October is when the time changes in LA).

Otherwise, the time is going to be wrong all the time.

Thanks!
